### ISSUE TITLE
Transformation Issue

### ISSUE THREAD

**Issue by managedcoder** [VSSolutionTemplates/JumpStreetMobile#3]
Using the latest .vsix there are issues with the solution generation process.  See the email I sent for screen shots that make the follow much clearer:
- Generated solution only includes the one project instead of all of them
- Project folders are correctly named but not correctly named in solution so those project don't load
- Namespace and other occurrences of JumpStreetMobile don't get replaced properly with the solution name that the developer provided during File | New

**Comment by sayedihashimi** [comment]
Should be fixed now
